### ISSUE TITLE
Cordova and CORS? (Ws4 beta7)

### ISSUE THREAD

**Issue by o1lo01ol1o** [dotnet-websharper/ui#126]
I have a standalone Owin client server app acting as a backend for a Cordova mobile app.  The latter is pointed at the former's localhost:port and the former has a `WebSharper.Web.Remoting.AddAllowedOrigin(localhost:appport)` however, the client keeps claiming the server does provide the necessary headers for the cors request. I'vet tried diabling csrf protection but nothing has appeased the daemon. 

 Is this architecture supported in Ws4?

**Comment by Tarmil** [comment]
Yes, in fact the origin that needs to be added is not the server backend url, but the local url of the web page as served internally by Cordova to the mobile web view. In a project I'm working on, I have the following:

        WebSharper.Web.Remoting.AddAllowedOrigin("null")
        WebSharper.Web.Remoting.AddAllowedOrigin("file://")

IIRC the former is what gets set on Android and the latter on iOS, or vice-versa.
