### ISSUE TITLE
Strange rendering from templating

### ISSUE THREAD

**Issue by Micha-kun** [dotnet-websharper/ui#130]
Hi, I don't understand if it's only me, but in my html template I'm working on a navbar bootstrap with a form, currently with static data:

```
<form class="navbar-form navbar-right visible-xs" role="search">
  <div class="navbar-right visible-xs">
    <select class="form-control">
      <option>ES</option>
      <option>CA</option>
      <option>EN</option>
    </select>
  </div>
</form>
```

But, when rendering on browser, WebSharper generates this!

```
<form class="navbar-form navbar-right visible-xs" role="search"></form>
  <div class="navbar-right visible-xs">
    <select class="form-control">
      <option></option>ES
      <option></option>CA
      <option></option>EN
    </select>
   </div>
&lt;/form&gt;
```

I don't understand why is generating this html, it's static!

Currently using Zafir.UI.Next 4.0.155.64-beta8

**Comment by granicz** [comment]
Can you give some context here - are you using this template on the client or the server side?  Also, can you post your instantiating code?

**Comment by Micha-kun** [comment]
I'm using this on the server side using Suave integration (Zafir.Suave 4.0.90.43-beta8)

About the instantiating code, you mean this?

```
open WebSharper.UI.Next.Server

type EndPoint =
    | [<EndPoint "/">] Home
    | [<EndPoint "/about">] About

module Templating =
    open WebSharper.UI.Next.Html

    type MainTemplate = Templating.Template<"Main.html">

    // Compute a menubar where the menu item for the given endpoint is active
    let MenuBar (ctx: Context<EndPoint>) endpoint : Doc list =
        let ( => ) txt act =
             liAttr [if endpoint = act then yield attr.``class`` "active"] [
                aAttr [attr.href (ctx.Link act)] [text txt]
             ]
        [
            li ["Home" => EndPoint.Home]
            li ["About" => EndPoint.About]
        ]

    let Main ctx action (title: string) (body: Doc list) =
        Content.Page(
            MainTemplate()
                .Title(title)
                .MenuBar(MenuBar ctx action)
                .MenuBarSecondary(MenuBar ctx action)
                .Body(body)
                .Doc()
        )

module Site =
    open WebSharper.UI.Next.Html

    let HomePage ctx : Async<Content<EndPoint>> =
        Templating.Main ctx EndPoint.Home "Home" [
            h1 [text "Say Hi to the server!"]
            div [client <@ Client.Main() @>]
        ]
```

I'm only extending the base template generated by websharper project template using VS2017.

**Comment by granicz** [comment]
I can indeed confirm this issue, with certain HTML tags like `form` and `select`. @Tarmil - can you take a look?

(BTW, I believe you are missing a reference to Bootstrap from your template, as well.)

**Comment by Micha-kun** [comment]
About the bootstrap reference I'm using this mechanism:

```
module Resources =
    open WebSharper.Core.Resources
    

    module Bootstrap =
        type Css() =
            inherit BaseResource("https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css")
        
        [<Require(typeof<WebSharper.JQuery.Resources.JQuery>)>]
        type Js() =
            inherit BaseResource("https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js")

    module FontAwesome =
        type Css() =
            inherit BaseResource("https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css")
    
    [<Require(typeof<Bootstrap.Css>)>]
    [<Require(typeof<FontAwesome.Css>)>]
    type Css()=
        inherit BaseResource("main.min.css")
```

Is there any problem with this approach?

**Comment by Tarmil** [comment]
No, the resource handling is good. I'm now looking at the templating issue.

**Comment by Tarmil** [comment]
This seems to be an issue with HtmlAgilityPack; more specifically, [this one](https://github.com/zzzprojects/html-agility-pack/issues/45) for the form tag and [this one](https://github.com/zzzprojects/html-agility-pack/issues/48) for the option tag. It is strange though that they were both only reported in the last 2 weeks, because based on my local tests, it was already an issue in HtmlAgilityPack 1.4.9.5 from a year ago.

**Comment by Micha-kun** [comment]
HtmlAgilityPack released a new prerelease (https://www.nuget.org/packages/HtmlAgilityPack/1.5.2-beta4) that _seems_ to fix the problem. Now form shows fine. But select's options still have an invalid rendering. It can render fine options if the data comes from attributes, but meh... Something so basic...

**Comment by granicz** [comment]
Yeah, that's pretty crazy indeed.  Have you tried using `<option>ES`, etc., e.g. without the closing tag?

**Comment by Micha-kun** [comment]
Doesn't work:

```
<select class="form-control">
   <option></option>ES
   <option></option>CA
   <option></option>EN
</select>
```

**Comment by Tarmil** [comment]
HtmlAgilityPack's latest release (v1.6.6) fixes the `<option>` issue. We'll include it in next release of UI.Next.

**Comment by Tarmil** [comment]
This was done in v4.1.
