### ISSUE TITLE
Unfilled `ws-replace` holes are not removed

### ISSUE THREAD

**Issue by Jand42** [dotnet-websharper/ui#131]
If a template has `<div ws-replace="ReplaceThis">This should be replaced</div>` and this hole is not filled by `.ReplaceThis(...)` when instantiating a template, the div node gets inserted with the `ws-replace` attribute and all content intact.

Expected: not calling `.ReplaceThis(...)` should behave like calling `.ReplaceThis(Doc.Empty)`, not including the element.

**Comment by AlexPeret** [comment]
hi!

calling `.ReplaceThis(Doc.Empty)` is throwing the following exception:

> TypeError: $1 is null

Replacing it by an empty element (say: `.ReplaceThis(div [] :> Doc)`) works fine.

Please, find the (partial) stack trace at the end and let me know if you want me to submit a new ticket.

Alex

> Docs$1.InsertDoc/< - http://localhost:50621/Scripts/WebSharper/WebSharper.UI.Next.js:3792:4
> Arrays.foldBack - ArrayModule.fs:174:15
> Docs$1.InsertDoc - http://localhost:50621/Scripts/WebSharper/WebSharper.UI.Next.js:3790:309
> Docs$1.InsertDoc - http://localhost:50621/Scripts/WebSharper/WebSharper.UI.Next.js:3793:52
> Docs$1.LinkElement - http://localhost:50621/Scripts/WebSharper/WebSharper.UI.Next.js:3753:3
> Docs$1.CreateElemNode - http://localhost:50621/Scripts/WebSharper/WebSharper.UI.Next.js:3682:3
> Elt.New - http://localhost:50621/Scripts/WebSharper/WebSharper.UI.Next.js:5344:8
> Doc.Element - http://localhost:50621/Scripts/WebSharper/WebSharper.UI.Next.js:3908:10
> ...
>
