### ISSUE TITLE
Server-side event can cause JS runtime error

### ISSUE THREAD

**Issue by Jand42** [dotnet-websharper/ui#155]
Events in server-side templating translate to a call to `WebSharper.UI.Templating.Runtime.Server.Handler.EventQ2$120$42` but the script link to `WebSharper.UI.Templating.Runtime.js` might be missing because Sitelet runtime is not adding it.

For example:

Add a `<button ws-onclick="Click">Click me</button>` to a client-server template and use it at template instantiation as `.Click(fun _ -> JavaScript.JS.Alert "Clicked!")`

**Comment by Tarmil** [comment]
Actually, as I just tested this, it's not `WebSharper.UI.Templating.Runtime.js` that's missing, but the current project's js. `EventQ2$120$42` is there, but the function called as argument to it is not.
