### ISSUE TITLE
Add `Attr.DynamicClassPred`

### ISSUE THREAD

**Issue by granicz** [dotnet-websharper/ui#157]
We currently have `Attr.DynamicClass` to set a CSS class when a view satisfies a given predicate. This could benefit from an `Attr.DynamicClassPred` variant that takes a `View<bool>` instead of the `View<'T>` and the `'T -> bool` predicate.

**Comment by Tarmil** [comment]
Here's the full list of changes I intend to do:

* Add the following:
    ```fsharp
    val DynamicClassPred : name: string -> isSet: View<bool> -> Attr

    // V-enabled on `isSet`, which makes it compile into DynamicClassPred
    val ClassPred : name: string -> isSet: bool -> Attr
    ```

* Mark the current `DynamicClass` as obsolete, pointing to ClassPred and DynamicClassPred as replacements.
