### ISSUE TITLE
Allow binding template holes to the document

### ISSUE THREAD

**Issue by Tarmil** [dotnet-websharper/ui#161]
It would be nice to be able to fill holes directly into the document on the client side. For example instead of having to do something like this:

```html
<div id="main" ws-children-template="main">
  <button ws-onclick="Click">Click me</button>
</div>
```

```fsharp
[<SPAEntryPoint>]
let Main() =
    Template.main()
        .Click(fun e -> ())
        .Doc()
    |> Doc.RunById "main"
```

we would be able to do this:

```html
<div id="main">
  <button ws-onclick="Click">Click me</button>
</div>
```

```fsharp
[<SPAEntryPoint>]
let Main() =
    Template()
        .Click(fun e -> ())
        .Bind()
```

and no elements would be removed and re-rendered, instead the event handler would be added directly to the document.

**Comment by Tarmil** [comment]
I have a working implementation for SPAs. A question now is what to do when the page is served from a sitelet. The server-side templating will have purged all holes from the page, so there is nothing left to bind on the client side. The simplest solution is probably to add an option for server-side templates to not purge holes. There are two possibilities for this:

1. Put this as an extra static parameter to the type provider.
2. Put this as an optional argument to `.Doc()`.

I believe solution 2 is better, as it leaves the possibility to instantiate the same template in different sitelet endpoints, some of which use client-side `.Bind()` and others don't.

**Comment by granicz** [comment]
Agreed on 2, something like `.Doc(removeTemplates=true/false)` would work best.

**Comment by granicz** [comment]
Partially released (client-side `.Bind()` support) in [WebSharper UI 4.2.3.111](https://github.com/dotnet-websharper/ui/releases/tag/4.2.3.111).

**Comment by Tarmil** [comment]
Closing this ticket, as it is implemented and working well in SPAs. Related work to make Sitelets more amenable to it is in #163.
