### ISSUE TITLE
Doc.Checkbox: clicking the checkbox sets the Var twice

### ISSUE THREAD

**Issue by Tarmil** [dotnet-websharper/ui#164]

**Comment by Tarmil** [comment]
This is because we bind both the `click` and `change` event. I think we should be able to just remove the `click` handler: searching around, it seems `change` is supported everywhere. Although I don't have Internet Explorer handy to verify that.

**Comment by Jooseppi12** [comment]
In IE (9 and above definitely) `change` is supported as well. But there is one thing which should be definitely considered:
In Firefox and Chrome `click` is fired before `change`, but in IE and Edge `change` is fired before `click`.
