### ISSUE TITLE
Method name not found in JavaScript compilation

### ISSUE THREAD

**Issue by AndreiDegtiarev** [dotnet-websharper/ui#166]
After migration from Websharper.UI.Next to Websharper.UI, the code

```fsharp
let Main () = (div[] []).OnMouseDown(fun _ _ ->()) 
```

yields the build error:

```text
error FS9001: Method name not found in JavaScript compilation: (OnMouseDown : Microsoft.FSharp.Quotations.FSharpExpr`1<(WebSharper.JavaScript.Dom.Element -> (WebSharper.JavaScript.Dom.MouseEvent -> unit))> -> WebSharper.UI.Elt), Members: get_Element, AddClass', ClearHoles, AddHole, onExpr, SetStyle', HasClass', RemoveClass', GetProperty', SetProperty', RemoveAttribute', HasAttribute', GetAttribute', SetAttribute', SetText, GetText, SetValue, GetValue, Id', Html', Clear', PrependDoc, AppendDoc, TreeNode, New, ToUpdater, OnAfterRenderView, OnAfterRender, onView, on
```

**Comment by granicz** [comment]
I believe the update to UI didn't go correctly in your project - the above code should still work just fine. You might want to remove all UI.Next references (confirming in the project files as well) and re-adding the UI ones.

**Comment by Tarmil** [comment]
Actually I think this is because we are missing proxies for the quotation-based version of these methods. We should definitely (re-?)add them. But in the meantime, you should use `open WebSharper.UI.Client` to bring the client-side only, non-quotation-based method.

**Comment by AndreiDegtiarev** [comment]
Could you please point me how I can use “WebSharper.UI.Client” for handling of mouse events?

**Comment by RobBarton** [comment]
I encountered the same problem during a 3 -> 4 upgrade.  This might work for you:
`let Main () = DocExtensions.OnMouseDown (div [] [], fun _ _ -> ())`

**Comment by Tarmil** [comment]
Or you can set the event handler as an attribute:

```fsharp
let Main () =
    div [ on.mouseDown (fun _ _ -> ()) ] []
```

**Comment by AndreiDegtiarev** [comment]
Thank you for the help. It works now.
