### ISSUE TITLE
Shouldn't Elt.Empty return an Elt instead of a Doc?

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet-websharper/ui#169]
Just asking. There is already a `Doc.Empty`.

I guess, because the `Elt` type specifically refers to a _single_ element, it cannot be empty.

If that's the case, I think `Elt.Empty` should be marked as obsolete, as it is misleading.

**Comment by Tarmil** [comment]
`Elt.Empty` is actually just `Doc.Empty`. `Elt` inherits from `Doc`, so you can call static members of the `Doc` type from `Elt`.

**Comment by Tarmil** [comment]
Although this can be a bit confusing, I'm closing it as not really an issue. Maybe it will be alleviated if one day we revisit the current design to eg move members like Empty into a module rather than have them as static members, but for now this is minor enough to leave as is.
