### ISSUE TITLE
Template instantiation not yet supported on the server side

### ISSUE THREAD

**Issue by amieres** [dotnet-websharper/ui#171]
Two things
- Login is not working on the WebSharper.com site.
A big dialog that says "Login wasn't successful" keeps popping up no matter what option is selected.

- I'm trying to use Templates with the `FromDocument` option on the client with a page served by the server that includes the templates. The idea is to be able to change the file and refresh the browser to see the changes but I get the exception `Template instantiation not yet supported on the server side` 

How can I serve a page that includes Remoting functions and server content with templates that can be modified without recompiling?

**Comment by granicz** [comment]
Can you retry logging in with your cache cleared?

**Comment by Tarmil** [comment]
What this error message means by "Template instantiation" is the feature where you instantiate a subtemplate directly in the HTML file using a `<ws-MyTemplate>` tag. That is indeed currently only supported on the client side. Even though in your case these are indeed intended to be used on the client side, the server side is still confused by these `<ws-*>` tags. That's definitely something we need to improve.

Your workaround for now is to instead instantiate these in F# (which I know is far from ideal). For example if you have something like this:

```html
<div ws-template="MyTpl">${Content}</div>
<ws-MyTpl>
  <Content>Hello world!</Content>
</ws-MyTpl>
```

```fsharp
Template()
    .Doc()
```

Then you need to do something like this:

```html
<div ws-template="MyTpl">${Content}</div>
<div ws-replace="MyTplHole"></div>
```

```fsharp
Template()
    .MyTplHole(Template.MyTpl().Content("Hello world!").Doc())
    .Doc()
```

**Comment by amieres** [comment]
Thanks for the help.
In the end I placed the templates in a separate file which I reference for compilation and when serving the page I read the file and inject the code into the page using Verbatim:

```
    let content (ctx:Context<EndPoint>) (endpoint:EndPoint) : Async<Content<EndPoint>> =
        Content.Page(Title = "Main Page" 
                   , Body = [
                       Html.client <@  main() |> renderDoc @> 
                       Doc.Verbatim (System.IO.File.ReadAllText TemplatesFileName)
                     ])
```

It works very well! I can refresh without having to recompile.

**Comment by Tarmil** [comment]
Hi, I just pushed a fix for this. In UI 4.2.6 you'll be able to use client-side `<ws-*>` instantiation with a server-side rendered with `Template().Doc()`.

**Comment by Tarmil** [comment]
I'll close this issue about client-side `<ws-*>` in a sitelet, which is now fixed on master (and should be released to nuget soon), and open a separate one for the related use case of actually instantiating templates on the server side.
