### ISSUE TITLE
First time installing WebSharper and then NuGet of Ui.Next fails with assembly version mismatch

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet-websharper/ui#172]
If you're just "getting started", that is, 

* first time installation of WebSharper using the VSIX installer, 
* create a project "Websharper 4 Client/Server application", .NET version 4.7
* Execute suggested command for Ui.Next: ` Install-Package WebSharper.UI.Next -Version 4.2.0.187 `
* Run (F5) the sample code

Then the browser will show a YSOD with version mismatch on `HmtlAgilityPack`, specifically:

> `Could not load file or assembly 'HtmlAgilityPack, Version=1.7.1.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

The NuGet command gives a hint, it shows the following warning:

> One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'WebSharper.UI 4.2.5.115 constraint: System.Xml.XDocument (>= 4.3.0)', 'WebSharper.UI 4.2.5.115 constraint: HtmlAgilityPack (>= 1.7.1)'

When building, the following warning is displayed:

> `No way to resolve conflict between "HtmlAgilityPack, Version=1.7.1.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a" and "HtmlAgilityPack, Version=1.6.17.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a". Choosing "HtmlAgilityPack, Version=1.7.1.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a" arbitrarily.`

After which the YSOD comes around, mentioned above.

Here's the full output from NuGet (VS 2017 Pro, 15.6.6):

```text
PM> Install-Package WebSharper.UI.Next -Version 4.2.0.187 
Attempting to gather dependency information for package 'WebSharper.UI.Next.4.2.0.187' with respect to project 'Eriks Persoonlijke Gegevens', targeting '.NETFramework,Version=v4.7'
Gathering dependency information took 3,45 sec
Attempting to resolve dependencies for package 'WebSharper.UI.Next.4.2.0.187' with DependencyBehavior 'Lowest'
One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'WebSharper.UI 4.2.5.115 constraint: System.Xml.XDocument (>= 4.3.0)', 'WebSharper.UI 4.2.5.115 constraint: HtmlAgilityPack (>= 1.7.1)'
Resolving dependency information took 0 ms
Resolving actions to install package 'WebSharper.UI.Next.4.2.0.187'
Resolved actions to install package 'WebSharper.UI.Next.4.2.0.187'
Retrieving package 'WebSharper.UI.Next 4.2.0.187' from 'NuGet official package source'.
  GET https://www.nuget.org/api/v2/package/WebSharper.UI.Next/4.2.0.187
  OK https://www.nuget.org/api/v2/package/WebSharper.UI.Next/4.2.0.187 810ms
Installing WebSharper.UI.Next 4.2.0.187.
Adding package 'WebSharper.UI.Next.4.2.0.187' to folder 'D:\Projects\Test\packages'
Added package 'WebSharper.UI.Next.4.2.0.187' to folder 'D:\Projects\Test\packages'
Added package 'WebSharper.UI.Next.4.2.0.187' to 'packages.config'
Executing script file 'D:\Projects\Test\packages\WebSharper.UI.Next.4.2.0.187\tools\install.ps1'
Successfully installed 'WebSharper.UI.Next 4.2.0.187' to Eriks Persoonlijke Gegevens
Executing nuget actions took 6,06 sec
Time Elapsed: 00:00:09.6518532
```

Perhaps I'm doing something wrong, but I think the cycle "Fresh install of Websharper, then NuGet the Ui.Next package" should succeed.

It won't be too hard to resolve this, I can fix the references I think, but would be nice if this could be resolved.

I also noticed that this project references a rather older version of FSharp.Core (namely 4.2.3, Aug 19, 2017). Whether that is by design, I don't know, the current RTM version as of this writing is 4.3.4.

One resolution that seems to work so far is:

* Download recent version of HtmlAgilityPack through NuGet (I used 1.8)
* Download recent version of `System.XDocument` through NuGet (I used 4.3)
* Update `web.config` as follows, that is, add a dependency-redirect:
```xml
<dependentAssembly>
   <assemblyIdentity name="HtmlAgilityPack" publicKeyToken="bd319b19eaf3b43a" culture="neutral" />
   <bindingRedirect oldVersion="0.0.0.0-1.8.0.0" newVersion="1.8.0.0" />
</dependentAssembly>
```

I don't know if this is the "proper way" of resolving this, though. Just experimenting... ;).

**Comment by Tarmil** [comment]
It seems you are following outdated install instructions; `WebSharper.UI.Next` has been renamed to `WebSharper.UI`, so you should install and use that instead. Where did you get the install instructions from?

**Comment by abelbraaksma** [comment]
@Tarmil, tx, 

> Where did you get the install instructions from?

I got them from [the homepage of this Github](https://www.nuget.org/packages/WebSharper.UI.Next), then clicked on [Tutorial and Documentation](https://github.com/dotnet-websharper/ui/blob/master/docs/UINext.md), which links to the [NuGet page under section 'Availabiliy'](https://www.nuget.org/packages/WebSharper.UI.Next), which shows the command `Install-Package WebSharper.UI.Next -Version 4.2.0.187`.

Note that I originally tried to follow Adam's video tutorial, but that tutorial doesn't mention how to get the templates, which I still don't have, so I tried to experiment.

**Comment by abelbraaksma** [comment]
But perhaps the more important question is then: what are the proper instructions and where to find them? I may not be the only one running into this and I wasn't aware of WebSharper.UI.Next being renamed into WebSharper.UI.

**Comment by abelbraaksma** [comment]
From the look of it, every link on the UI project page links to UI.Next. Some of them empty with no furhter links (like the first one with "Examples", `https://github.com/dotnet-websharper/ui`, it links to an empty page on downloading, but without download link or instructions). And the `UI.Next` page has latest version one month old, sounds like it is still actively developed? 

I'll try to download the UI (not UI.Next) version from NuGet. See how that goes ;).

**Comment by Tarmil** [comment]
Ouch, yeah we definitely need to update this documentation.

UI is the new name of UI.Next, so it completely replaces it. We still release versions of UI.Next so that legacy projects can use new releases of the WebSharper compiler, but new projects should use UI.

The application projects in the VSIX already include UI, so you don't need to add anything.

**Comment by Tarmil** [comment]
Note that for documentation you should look here instead: https://developers.websharper.com/docs/v4.x/fs/ui

**Comment by abelbraaksma** [comment]
Thanks, found it meanwhile, but as you may agree, as a newcomer to the scene, that's pretty hard to find if you click through the homepage and follow some links.

Would like me to close this issue or should it remain open as a reminder?

**Comment by Tarmil** [comment]
Let's keep it open. I've changed the "Tutorial and documentation" link in the README to point to the above developers.websharper.com page, but we still need to update the linked examples as well.

**Comment by Tarmil** [comment]
The examples site is now updated to WebSharper.UI. http://intellifactory.github.io/websharper.ui.next.samples/#samples/samples/SimpleTextBox

**Comment by abelbraaksma** [comment]
Great! Thanks!
