### ISSUE TITLE
Implement template instantiation on the server side

### ISSUE THREAD

**Issue by Tarmil** [dotnet-websharper/ui#175]
Currently if a server-side template tries to use `<ws-*>` instantiation, it fails at runtime.

**Comment by Jand42** [comment]
Current progress:
* Text and Doc holes work.
Might work, needs tests:
- [ ] attributes,
- [ ] compound text content,
- [ ] hole mapping
TODO:
- [ ] multiple file cross-referencing

**Comment by Jand42** [comment]
Further concerns:
- [ ] single hole template filled in with direct content

Optimizing sub-template loading from another file:
- [ ] Separate method from GetOrLoadTemplate
- [ ] Change queue to a dictionary and only load other file when it is actually needed the first time
