### ISSUE TITLE
Cannot compile default project on dotnet-core version 2.1.4 on linux

### ISSUE THREAD

**Issue by vincenzoml** [dotnet-websharper/ui#178]
I would like to use WebSharper, but when I just create a default project either with the `-web` or with the `-html` template, I get the errors below. Any hint?

```
FSC : parse warning FS3005: Referenced assembly '/home/vincenzo/.nuget/packages/websharper.ui/4.2.6.118/lib/netstandard2.0/WebSharper.UI.Templating.dll' has assembly level attribute 'Microsoft.FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute' but no public type provider classes were found [/home/vincenzo/data/jesus/repos/imgql/test3/test3.fsproj]
parse error FS3053 : The type provider 'WebSharper.UI.Templating.TemplatingProvider' reported an error : The type provider constructor has thrown an exception: Could not load type 'WebSharper.UI.Templating.TemplatingProvider' from assembly 'WebSharper.UI.Templating, Version=4.2.0.0, Culture=neutral, PublicKeyToken=dcd983dec8f76a71'. 
```

**Comment by Tarmil** [comment]
Hi, I think the problem here is that unfortunately right now the WebSharper compiler still needs Mono installed to run on OSX and Linux. The resulting application is .NET Standard and can run with only .NET Core installed; but the compilation itself needs Mono.

We are working on running the compiler on .NET Core, so that this won't be an issue anymore. You can follow the progress at dotnet-websharper/core#941. I don't have a precise ETA for it, but I expect that it should be a couple weeks at most.

**Comment by vincenzoml** [comment]
Thanks! Following that issue.

**Comment by Tarmil** [comment]
Hi! WebSharper 4.3 is now out and does not require mono anymore.

**Comment by dulguuned** [comment]
Hello. How to run Websharper without mono? 

I added SqlProvider package by nuget and i run it from vs code terminal with dotnet run command and i get this error.

How to fix this error.

I set <WebSharperUseNetFxCompiler>true</WebSharperUseNetFxCompiler> in .fsproj and i get this error:

/usr/local/share/dotnet/sdk/2.1.302/FSharp/Microsoft.FSharp.Targets(263,9): error MSB6006: "wsfsc.exe" exited with code 8. [/Users/enkhdulguun/Documents/snapify_fsharp_api/snapify_fsharp_api.fsproj]

and if i remove <WebSharperUseNetFxCompiler>true</WebSharperUseNetFxCompiler> in .fsproj

i get this error:

FSC : parse warning FS3186: An error occurred while reading the F# metadata node at position 1 in table 'itycons' of assembly 'WebSharper.Core.JavaScript, Version=4.5.0.0, Culture=neutral, PublicKeyToken=dcd983dec8f76a71'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using. [/Users/enkhdulguun/Documents/snapify_fsharp_api/snapify_fsharp_api.fsproj]
FSC : parse warning FS3186: An error occurred while reading the F# metadata node at position 0 in table 'ivals' of assembly 'WebSharper.Core.JavaScript, Version=4.5.0.0, Culture=neutral, PublicKeyToken=dcd983dec8f76a71'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using. [/Users/enkhdulguun/Documents/snapify_fsharp_api/snapify_fsharp_api.fsproj]
\Users\enkhdulguun\Documents\snapify_fsharp_api\Site.fs(25,9,29,42): typecheck error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Could not load file or assembly 'System.Data.SqlClient, Version=4.2.0.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621) [/Users/enkhdulguun/Documents/snapify_fsharp_api/snapify_fsharp_api.fsproj]
\Users\enkhdulguun\Documents\snapify_fsharp_api\Site.fs(25,9,29,42): typecheck error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Could not load file or assembly 'System.Data.SqlClient, Version=4.2.0.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621) [/Users/enkhdulguun/Documents/snapify_fsharp_api/snapify_fsharp_api.fsproj]
\Users\enkhdulguun\Documents\snapify_fsharp_api\Site.fs(31,23,31,37): typecheck error FS0039: The field, constructor or member 'GetDataContext' is not defined. [/Users/enkhdulguun/Documents/snapify_fsharp_api/snapify_fsharp_api.fsproj]

The build failed. Please fix the build errors and run again.
