### ISSUE TITLE
Make HTML functions return Doc, have extra Elt.x functions that return Elt

### ISSUE THREAD

**Issue by Tarmil** [dotnet-websharper/ui#183]
With the hindsight from using UI in many applications, I've come to the conclusion that:

* The *vast* majority of use cases for DOM elements do not make any use of `Elt`-specific APIs like `.Dom`, `.OnEvent`, `.AppendDoc`, etc and could just as well have type `Doc`.
* There are many situations where we need to upcast from `Elt` to `Doc`, which is more verbose than necessary.

    Examples:

    * Branches with different types:

        ```fsharp
        if someCondition then
            Doc.Empty
        else
            span [] [text "test"] :> Doc
        ```

    * Higher-order functions:

        ```fsharp
        let mkList (count: int) (generate: int -> Doc) =
            ul [] [for i in 1..count do yield li [] [generate i]]

        let elt = mkList 10 (fun i -> span [] [text (string i)] :> Doc)
        ```

    * Lists that the compiler would otherwise mistakenly think are heterogeneous:

        ```fsharp
        [
            Doc.Empty
            span [] [text "haha"] :> Doc
        ]
        ```

    * `yield` ([this one will apparently be fixed in F# 4.5](https://github.com/fsharp/fslang-design/blob/master/FSharp-4.5/FS-1055-subsumption-for-yield-in-sequence-expression.md)):

        ```fsharp
        div [] [
            yield span [] [text "test"] :> Doc
            if someCondition then
                yield a [attr.href "/"] [text "test"] :> Doc
        ]
        ```

I therefore propose that:

* Functions such as `div`, `span`, etc from the `WebSharper.UI.Html` module should return type `Doc` instead of `Elt`.
* A new module `WebSharper.UI.Html.Elt` should be added, with these same functions returning `Elt`.

Obviously this is a breaking change, but I think it's a worthwile one that will both make learning easier and real-life code more readable.

Note that this only concerns the F# API; C# performs enough automatic upcasting that this is not problematic there.

**Comment by cata** [comment]
@Tarmil I'm all for it. I can't think of one single case where we use `Elt`-specific functions in our code. on the other hand,  upcasts from `Elt` to `Doc` are pervasive.

**Comment by Tarmil** [comment]
Change applied in 6be098a.
