### ISSUE TITLE
erro FS9001: No macro fallback found for 'WebSharper.UI.Macros+AttrProp'

### ISSUE THREAD

**Issue by AlexPeret** [dotnet-websharper/ui#210]
hi,

the compiler is emitting the error below, if the Attr.Prop function is used:

> erro FS9001: No macro fallback found for 'WebSharper.UI.Macros+AttrProp'

this line doesn't work:
`Attr.Prop "max" "10"`

but this one works
`attr.max "10"`

**WebSharper version**: 4.5.11.334

Thanks,
Alex

**Comment by Jand42** [comment]
@AlexPeret Thanks for the report, indeed an attribute is missing for this to work, fix coming soon.

**Comment by Jand42** [comment]
@AlexPeret Hi, the fix is now public in https://github.com/dotnet-websharper/ui/releases/tag/4.5.10.166

**Comment by AlexPeret** [comment]
> 
> 
> @AlexPeret Hi, the fix is now public in https://github.com/dotnet-websharper/ui/releases/tag/4.5.10.166

thank you!
