### ISSUE TITLE
attr.disabledDyn has wrong signature

### ISSUE THREAD

**Issue by AlexPeret** [dotnet-websharper/ui#217]
Hi!

the [disabledDyn extension function](https://github.com/dotnet-websharper/ui/blob/78aaf0684c006f4ce0cad208fd40849ad8d73c75/WebSharper.UI/HTML.Client.fs#L488
) is requiring a `View<string>` instead of `View<bool>` as parameter:

``` fsharp
[<AutoOpen>]
module HtmlExtensions =

    type Html.attr with
        ...
        /// Create an HTML attribute "disabled" with the given reactive value.
        [<JavaScript; Inline>]
        static member disabledDyn view = Client.Attr.Dynamic "disabled" view
        ...
```

This is the error message I see on tooltip:
``` fsharp
static member disabledDyn: view: View<string> -> Attr
```

Thanks!

**Comment by btamas2000** [comment]
Hey! Solution for this is in #221
