### ISSUE TITLE
Obsolete `client`

### ISSUE THREAD

**Issue by Jand42** [dotnet-websharper/ui#241]
In favor of `Doc.ClientSide` which supports auto-quoting expression argument.

**Comment by granicz** [comment]
We need to revert this, in favor of the direction set forth in #240 .

**Comment by granicz** [comment]
Just a quick summary: `Doc.ClientSide` is gone, `open type WebSharper.UI.ClientServer` and use `client` instead, without the `<@ ... @>` delimiters.
