### ISSUE TITLE
Rendering of a whole document hangs for the duration of the async block of a dependent View.MapAsync

### ISSUE THREAD

**Issue by qwe2** [dotnet-websharper/ui#75]

**Comment by Jand42** [comment]
Reproduction: http://try.websharper.com/snippet/JankoA/0000Od

**Comment by Jand42** [comment]
Not changing behavior of MapAsync, but adding helpers to do a MapAsync followed by an WithInit, which solves this issue: rendering is not happening while any view is in waiting state. This will be easier to be avoided with new helpers MapAsyncLoading/MapAsyncOption. C# equivalents are just overloads of MapAsync.

**Comment by ArtemyB** [comment]
@Jand42 , I've noticed that currently there are no static versions of the functions `MapAsyncLoading` and `MapAsyncOption`. I suppose it wasn't by design and is just a little oversight. So decided to mention this.
